### ISSUE TITLE
404 for the bosonic polyfills

### ISSUE THREAD

**Issue by ariutta** [bosonic/bosonic#11]
The [Getting Started page](http://bosonic.github.io/getting-started.html) has a dead link for the bosonic polyfills:
https://github.com/bosonic/bosonic/raw/master/dist/bosonic-polyfills.js

**Comment by gervaisb** [comment]
+1

**Comment by rockdragon** [comment]
+1

**Comment by enguerran** [comment]
For now you have to use bosonic-platform.js and bosonic-runtime.js instead of bosonic-polyfill.js. @goldoraf will tell if I am wrong:
* bosonic-runtime.js polyfills HTMLImport
* bosonic-paltform.js polyfills what webcomponents.js (from Polymer) does. (although you can use whatever platform you want for bosonic web components)

By the way, a brand new website is coming. We just need some more time.
