### ISSUE TITLE
Css variables necessary?

### ISSUE THREAD

**Issue by Meai** [bosonic/bosonic#27]
It sounds like Css variables are the reason for a buildstep. Wouldn't it be better to use import rules. I read the discussion here about the deprecation of /deep/ selectors and they seem to suggest using css imports to reuse global css.

https://code.google.com/p/chromium/issues/detail?id=489954

@import url( '<path_to>/common-style.css' );

**Comment by goldoraf** [comment]
Using CSS Variables looks to me like the best way for elements' users to customize the elements' appearance (theming). The Polymer team has decided [to use CSS Variables/Properties](https://www.polymer-project.org/1.0/docs/devguide/styling.html#xscope-styling) too, because they feel that forcing users to use /deep/ and ::shadow selectors makes theming more difficult, and, as you mention it, these selectors are being deprecated. As for the buildstep, performance is my #1 priority, therefore I'm reluctant to use a CSS Variables polyfill. Moreover, I think a lot of developers already have some kind of build step in their workflow, for CSS post-processing or JS files concat or... That's my reasoning, but I'm open to discussion of course.

Regarding the CSS import suggestion, I must confess I don't see where the author is heading. Could you elaborate (with sample code ideally) on what he said?

**Comment by Meai1** [comment]
Okay maybe I misunderstood the full motivation for css variables, seems like there is no real better choice. I thought it was just about a global common css file. 

Something else: I would really remove all the grunt, npm and bower stuff. It's complicated and an extra step before I can use bosonic. I know the webcomponents tester seems nice but to me the output in the console isn't even useful, I cant jump to the source from there and I have to know to open it. 
I couldnt even get the bosonic core elements dialog test running until I changed "../node_modules/web-component-tester/browser.js"></script>" to "../bower_components/web-component-tester/browser.js"></script>"
The grunt task also seems to copy something around? I havent tried that because I dont have it setup on my PATH...
In my opinion "python3 -m http.server" should be more than enough to get an html site running, anything more is in my opinion too complicated and this includes npm or bower install steps.

I think the value from bosonic is that it isn't as complicated as polymer. That means I dont have 25 folders with all kinds of html and js imports. Instead one file and you import it and you are done. 
That's awesome. If you try to import polymer, it will import 5 other html imports, which will again import 5 other htmls .. that kind of approach is just in my opinion really bad. Who knows where the folders have to be for it all to work and if you move 1 file the wrong way it all breaks. 
I know it's just the tests for now but still.

Would you agree? All I'm saying here is: Maybe it's possible to completely remove npm, bower, grunt from the workflow and actually simplify it + put a single additional line into the readme: "you need a webserver for the html imports to work due to cross browser policy, you can do it e.g via python3 -m http.server"

I havent tried to replace the tests dependencies with something simpler yet, but I would much prefer a results site like here: http://webreflection.github.io/document-register-element/test/
I will look into how to do something like that myself but I wanted to see what you think about all of this.

**Comment by goldoraf** [comment]
I agree that __using__ Bosonic elements should be simple: that's why since the 1.0 I provide ZIP files of Bosonic's runtime and its elements, like [stated in the doc](http://bosonic.github.io/documentation/getting-started/getting-the-code.html). NPM install is no longer mandatory, yet there are lot of devs who already uses npm/grunt/whatever in their workflow and who are consequently happy to be able to install Bosonic with npm. As for the need of a webserver because of HTML imports, it's mentioned in the doc too (at the bottom of the page).

__developing__ Bosonic's runtime or new elements is a different thing: I use web-component-tester because I need to run the tests on as many browsers as possible (using SauceLabs for instance), and, as I tend to work in TDD mode, I need to run the tests very frequently, that's why it must be automated. If you wants to __use__ Bosonic, you don't have to run its wct tests: just download it and its elements, drop them into a web page and you're go. Maybe the problem here is Github in a sense: people are used to go to Github and to read the project's README to get started, but in the case of Bosonic, the README is here only for people who would like to contribute. If you simply intend to use Bosonic, the documentation is on the website. I'll modify the README to make it more clearer. Does it make sense to you?

One last thing: even if you can use Bosonic today without npm/bower/grunt, you'll probably want to concatenate elements into a single file before [putting your app into production](http://bosonic.github.io/documentation/getting-started/putting-into-production.html) in order to reduce the number of network requests. This is where task runners like grunt/gulp/make are useful: a lot of people already use that kind of tool to concatenate & minify their multiple JS files.

**Comment by Meai** [comment]
I think just about everyone who will use bosonic will use it for its hackability, therefore he will also want to write tests himself but okay
polymer seems like a better choice if you just want to use premade elements
